export const APILLON_BUCKET_UUID = process.env.NEXT_PUBLIC_APILLION_BUCKET_UUID;

export const APILLION_AUTH_SECRET =
  process.env.NEXT_PUBLIC_APILLION_AUTH_SECRET;

export const URL_ROOT = process.env.NEXT_PUBLIC_URL_ROOT;

export const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY!;
export const FIREBASE_AUTH_DOMAIN = process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN!;
export const FIREBASE_PROJECT_ID = process.env.NEXT_PUBLIC_PROJECT_ID!;
export const FIREBASE_STORAGE_BUCKET = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET!;
export const FIREBASE_MESSAGING_SENDER_ID = process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID!;
export const FIREBASE_APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APP_ID!;
export const FIREBASE_MEASUREMENT_ID = process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID!;
