export const APILLON_BUCKET_UUID = process.env.NEXT_PUBLIC_APILLION_BUCKET_UUID;

export const APILLION_AUTH_SECRET =
  process.env.NEXT_PUBLIC_APILLION_AUTH_SECRET;

export const URL_ROOT = process.env.NEXT_PUBLIC_URL_ROOT;
